# Generated by Django 5.0.3 on 2024-04-16 12:56

import api.users.user_models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/upload/profile_pic/default/Default-Profile-Picture-Transparent-Image.png', null=True, upload_to=api.users.user_models.user_model.Users.get_profile_pic_filename),
        ),
    ]
