# Generated by Django 5.0.3 on 2024-03-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_users_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagories",
            fields=[
                ("catagory_id", models.AutoField(primary_key=True, serialize=False)),
                ("catagory_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Catagories",
            },
        ),
    ]
